### PR TITLE
Chore: style gutenberg table same as c-table elements

### PR DESCRIPTION
**Pull request by derekshirk**
## Overview

See #710 

Adds visual front-end support for the following table styles generated via Gutenberg block editor. 

- Default
- Ruled (we get this by default without any additional CSS required)
- Stripped (uses available `is-style-stripes` style option)
- Numeric

## Screenshots

Screen Shot 2020-05-29 at 2 26 23 PM

Screen Shot 2020-05-29 at 2 26 34 PM

## Testing

1. View [theme deploy](https://deploy-preview-743--cloudfour-patterns.netlify.app/)
1. Confirm `c-table` component styles are unaffected
1. Observe `vendor/WordPress/gutenberg/core/table` example stories and confirm they appearance match the relevant component styles.
1. Confirm the description/notes for `vendor/WordPress/gutenberg/core/table` is free from typos and written clearly.

### CODE REVIEW

**Comment by calebeby** [comment]
@derekshirk The numeric table heading is missing the padding to make it vertically right-aligned with the cells:

WP numeric table:

image

Numeric table pattern:

image

**Comment by calebeby** [comment]
@derekshirk I don't know how to do the "bonus testing" steps:

I have WP set up

> enqueue the @v-next standalone css
> Confirm front-end table styles are rendered as expected with the block editor

I'm fine with skipping the bonus testing steps if you don't think I need to do them, but if you want me to do them, can you tell me how?

**Comment by derekshirk** [comment]
Converting back to draft mode while I address some issues.

**Comment by derekshirk** [comment]
This PR is now back open for review.

**Comment by derekshirk** [comment]
@tylersticka Would you like the opportunity to review this?

**Comment by tylersticka** [comment]
> @tylersticka Would you like the opportunity to review this?

Looks fine to me!

**Pull request merged**
