### PR TITLE
Prototypes/csl alt

### PR DESCRIPTION
**Pull request by AriannaChau**
## Overview

This PR does further work on the case study listings prototype page, but mainly focusing on the other sections, namely the Book and Open Source sections.

## Screenshots

**Book section on small screens:**
Screen Shot 2021-07-06 at 11 35 29 AM

**Book section on large screens:**
Screen Shot 2021-07-06 at 11 35 14 AM

**Open source section on small screens:**
Screen Shot 2021-07-06 at 11 36 02 AM

**Open source section on large screens:**
Screen Shot 2021-07-06 at 11 35 42 AM

## Testing

1. [Deploy link](https://deploy-preview-1366--cloudfour-patterns.netlify.app/iframe.html?id=prototypes-case-study-listings--example&args=&viewMode=story)

---

- Fixes https://github.com/cloudfour/cloudfour.com-patterns/issues/1337

### CODE REVIEW

**Review by tylersticka — COMMENTED** [review]
- The book and open source sections appear to be missing their headings and links.
- The GitHub link appears to be missing from the open source intro
- Consider using a single quotation character (`’`) instead of a straight apostrophe (`'`) for "we’ve."

**Review by tylersticka — COMMENTED** [review]
The section and cell headings feel misaligned right now. The secondary headings should not have a higher initial baseline compared to the section headings.

Screen Shot 2021-07-06 at 2 25 17 PM

**Review by tylersticka — COMMENTED** [review]
The baselines are now aligned between headings, but the images have been pushed down as well. We should retain the same image alignment as before.

**Review by tylersticka — COMMENTED** [review]
Can this action go beneath the project listing on small screens?

Screen Shot 2021-07-06 at 4 29 56 PM

**Comment by AriannaChau** [comment]
I've made the button full width on small screens, not sure if that's working but wanted your opinion.

Screen Shot 2021-07-06 at 4 59 16 PM

**Comment by tylersticka** [comment]
> I've made the button full width on small screens, not sure if that's working but wanted your opinion.

How do you think it should work instead?

**Comment by AriannaChau** [comment]
> > I've made the button full width on small screens, not sure if that's working but wanted your opinion.
> 
> How do you think it should work instead?

I could see is aligning to the left like it does on large screens like this,
Screen Shot 2021-07-07 at 8 48 20 AM


But I like it taking up the full width better.

**Comment by tylersticka** [comment]
@AriannaChau I'm open to either of those, so feel free to pick the one you feel best about.

**Review by tylersticka — APPROVED** [review]
@AriannaChau This PR is approved, but the task isn't finished until we integrate the client logos into the page design. That can be a separate issue if you'd like.

**Pull request merged**
