### PR TITLE
Fix: Replace problematic Map instance with multi-dimensional array

### PR DESCRIPTION
**Pull request by erikjung**
#324 

@tylersticka Wanna give this a whirl on your nicely installed IE11 VM?

**TL;DR** There was code using `Map`, which is not transformed by Babel, and is only partially supported by IE11. I'm guessing this was the issue.

/CC @mrgerardorodriguez

### CODE REVIEW

**Comment by mrgerardorodriguez** [comment]
Great catch @erikjung!

**Comment by tylersticka** [comment]
@erikjung New error:

virtualbox_ie11 - win7_19_07_2016_09_01_26

**Comment by erikjung** [comment]
I guess installing the VM is unavoidable.

**Comment by tylersticka** [comment]
@erikjung I can copy the OVA to a dive if it's faster.

**Comment by erikjung** [comment]
@tylersticka Wanna try once more? ^^^

**Comment by tylersticka** [comment]
@erikjung I think you need to install the VM. 😅 

virtualbox_ie11 - win7_19_07_2016_09_59_20

**Comment by erikjung** [comment]
@tylersticka 😭 

Yeah, if you want to put it on a drive, that'd be great.

**Comment by erikjung** [comment]
@tylersticka It appears to be all-to-the-good now.

screen shot 2016-07-19 at 10 52 38 am

**Comment by tylersticka** [comment]
LGTM :+1:

**Pull request merged**
