### PR TITLE
Add Speaking Listing prototype

### PR DESCRIPTION
**Pull request by dromo77**
## Overview

This PR adds a prototype of the speaking page. It's an overview of talks Cloud Four has given. The design similar to the [current page](https://cloudfour.com/presents/), but uses our new patterns.

## Screenshots

Screen Shot 2021-07-21 at 3 11 12 PM

---

- This is 1/2 of issue #1417. The other part will involve prototyping the individual pages.

### CODE REVIEW

**Review by tylersticka — COMMENTED** [review]
@dromo77 This should also include upcoming speaking engagements. Here's a link for reference from the original issue description:

> Prototype with upcoming events visible: https://cloudfour-patterns.netlify.app/pages/talk-core.html

Screen Shot 2021-07-21 at 3 59 38 PM

**Comment by dromo77** [comment]
@tylersticka I added a "Future Events" section at the beginning of the page. Would love your feedback now that all the content is there 🙂

**Review by tylersticka — COMMENTED** [review]
I like the individual content elements a lot.

Something's off about the spacing right now. 🤔 

Screen Shot 2021-07-22 at 11 59 50 AM

**Comment by dromo77** [comment]
@tylersticka I see what you mean. Here it is using the `o-rhythm--generous` modifier to increase the spacing between elements. The space between grid items is still larger, but it feels better to me. What do you think?

Screen Shot 2021-07-22 at 12 58 05 PM

**Review by tylersticka — APPROVED** [review]
Looks good! It looks like you needed some new CSS for this, so be sure to create issues representing any new patterns we may need to make this a reality.

**Pull request merged**
