### PR TITLE
Feature: CMS class

### PR DESCRIPTION
**Pull request by saralohr**
Add style to `pre` for WP-entered content. Couldn't think of anything else to add at the moment.

cc @mrgerardorodriguez @tylersticka

### CODE REVIEW

**Comment by saralohr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nFGuIPP4&#x2F;196-how-to-handle-wordpress-image-classes-plus-our-own-classes-and-components-in-blog-entry-both-new-and-old"> How to handle Wordpress image classes, plus our own classes and components in blog entry (both new and old)</a>

**Comment by tylersticka** [comment]
@saralohr Nice!

Should we have a pattern for this as well to document the component?

**Comment by saralohr** [comment]
> Should we have a pattern for this as well to document the component?
Doh, forgot about the pattern.

**Comment by saralohr** [comment]
@tylersticka Updated with pattern. 

cms-content

**Comment by tylersticka** [comment]
@saralohr Perfect! 👍

**Pull request merged**
