### PR TITLE
Add Quotes Prototype

### PR DESCRIPTION
**Pull request by dromo77**
## Overview

This PR adds a prototype with pull quote and block quote styles.

## Screenshots

Screen Shot 2021-09-23 at 10 50 11 AM

Screen Shot 2021-09-23 at 10 50 35 AM

## Testing
1. [Deploy Preview](https://deploy-preview-1551--cloudfour-patterns.netlify.app/?path=/story/prototypes-quotes--example)

---

-  #1521

### CODE REVIEW

**Comment by Paul-Hebert** [comment]
@dromo77 I wonder if we could remove the italics from block quotes as well so we don't lose the semantic meaning of italics in the text we quote? What do you think?

**Comment by tylersticka** [comment]
> I wonder if we could remove the italics from block quotes as well so we don't lose the semantic meaning of italics in the text we quote? What do you think?

I agree, I don't love the italics.

**Comment by dromo77** [comment]
@Paul-Hebert @tylersticka Sure thing
Screen Shot 2021-09-23 at 12 34 12 PM
!

**Comment by Paul-Hebert** [comment]
This looks good to me, but I'll defer final design approval to @tylersticka

**Review by tylersticka — APPROVED** [review]

**Pull request merged**
