### PR TITLE
Global nav tweaks

### PR DESCRIPTION
**Pull request by tylersticka**
I was _one_ page too optimistic when I designed nav stuff last year. So close! 😆 

This makes some nav-related tweaks...

1. Adds the latest nav item to the header and footer. (I do not know if these labels are final.)
2. Adjusts the `--Sky-nav-*-viewport` media queries to account for this change.
3. Adjusts the global footer since we've toppled the symmetry of the footer nav.
4. Makes two small tweaks tot he page segue that were bugging me.

---

@saralohr @mrgerardorodriguez @nicolemors @aileenjeffries

### CODE REVIEW

**Comment by saralohr** [comment]
Looks good!

**Comment by mrgerardorodriguez** [comment]
👍

**Comment by tylersticka** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;N8IuRTjX&#x2F;200-sketch-mockup-prototype-what-sets-us-apart"> Sketch&#x2F;Mockup&#x2F;Prototype: What Sets Us Apart</a>

**Comment by tylersticka** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;N8IuRTjX&#x2F;200-sketch-mockup-prototype-what-sets-us-apart"> Sketch&#x2F;Mockup&#x2F;Prototype: What Sets Us Apart</a>

**Comment by tylersticka** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;N8IuRTjX&#x2F;200-sketch-mockup-prototype-what-sets-us-apart"> Sketch&#x2F;Mockup&#x2F;Prototype: What Sets Us Apart</a>

**Pull request merged**
